# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f14026540f209b2d9f161ac0de49f1b6d3b3774128194afcea5b1de9524775d7539dfc70ff72678d30cbb0672f7bc3d30e34d797d9537e72839a1f87522725

test:
  secret_key_base: 49c8efeca55ad471175e10b611223713fdee1666e58a92fbd0aae922f209a7cc592b5ed2c6eaa655201c0c68858dbe3d3db3536e42b2456af6cf9ec1a33da293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
